### ISSUE TITLE
POST URL encoded form params are not parsed by default in falcon 1.0.0rc

### ISSUE THREAD

**Issue by fabregaszy** [yohanboniface/pytest-falcon#5]
After I updated falcon to latest 1.0.0, the pytest-falcon example test failed to execute.
It caused by falcon 1.0.0 now has options to control whether to auto parse params in url-encoded form and store them into params, ant this auto parse function is closed by default.

Code example
```
application = falcon.API()
if falcon.__version__ > '0.3.0':
    application.req_options.auto_parse_form_urlencoded = True
```

**Comment by yohanboniface** [comment]
Humm, how is that an issue for `pytest-falcon`?
If you don't set `req_options.auto_parse_form_urlencoded` it will not even work in your application. Or am I missing something?

**Comment by fabregaszy** [comment]
No, of course it isn't an issue for `pytest-falcon`.
But the code example in the `README.md` may not work for person who uses falcon 1.0.0.
And some newbie like me may get confused until I know the option `req_options.auto_parse_form_urlencoded`.

**Comment by yohanboniface** [comment]
Oh, I see, good point. Let's update the README to have a working example.
