### ISSUE TITLE
Test fails on included tests

### ISSUE THREAD

**Issue by ChiliConSql** [yohanboniface/pytest-falcon#6]
When I run py.test on the included tests/test_fixtures, it fails with the following error:

_KeyError: 'myparam'
tests/test_fixtures.py:74: KeyError_

Any ideas?

**Comment by yohanboniface** [comment]
git pull ;)

**Comment by yohanboniface** [comment]
See https://github.com/yohanboniface/pytest-falcon/commit/a58112c9eb080d024a00f5042f7cb5ebf0d3252f

**Comment by ChiliConSql** [comment]
Very nice. Thank you.
